version: '2'

services:

  elasticsearch:
    build: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx6g -Xms6g"
    restart: always

  logstash:
    build: logstash/
    volumes:
      - ./logstash/log:/var/log/logstash
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    build: kibana/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always
